### ISSUE TITLE
feat: 创建策略新增策略描述字段

### ISSUE THREAD

**Issue by 2020tracey** [TencentBlueKing/bk-audit#204]
创建策略时新增”描述“字段，非必填，多行文本框，1000字以内。注意策略详情页也需要展示该字段，若为空展示为--
<img width="1406" alt="image" src="https://github.com/TencentBlueKing/bk-audit/assets/154485076/16e1277b-26a1-4c9d-b06b-aa539dae661f">

**Comment by OrenZhang** [comment]
开发分支：[feat_strategy_desc](https://github.com/TencentBlueKing/bk-audit/tree/feat_strategy_desc)
