### ISSUE TITLE
feat: 权限申请操作名称优化

### ISSUE THREAD

**Issue by 2020tracey** [TencentBlueKing/bk-audit#207]
检索的操作名称改为”审计日志检索-非敏“       ”审计日志检索-敏感“    中间无用的高敏去掉
<img width="1202" alt="image" src="https://github.com/TencentBlueKing/bk-audit/assets/154485076/744b77bb-d4c6-4a1c-86f9-c93b1a0a4a59">

**Comment by OrenZhang** [comment]
开发分支：dev
