### ISSUE TITLE
feat: 处理套餐的参数映射支持文本输入

### ISSUE THREAD

**Issue by 2020tracey** [TencentBlueKing/bk-audit#208]
1、处理套餐的套餐参数配置需要支持文本输入（当前为下拉列表，需要既可以选择下拉选项，没有选项时也要支持输入文本）替换为策略配置中的检测条件配置的输入框

2、输入框中灰色提示文字为”请选择已有选项或自行输入内容后Enter结束“
![image](https://github.com/TencentBlueKing/bk-audit/assets/154485076/2947ce30-4587-4cbb-9be4-9b8bb702fb72)

**Comment by OrenZhang** [comment]
开发分支：feat_tool_const

**Comment by OrenZhang** [comment]
接口参数修改，当入餐为常量时，使用 value 字段存储用户输入的常量，field 字段可与 value 字段同时存在，但是以 value 优先

```json
{
    "pa_id": "56",
    "pa_params": {
        "${operator}": {
            "value": "xxx",
            "field": "xxx"
        }
    },
    "auto_close_risk": false
}
```
