### ISSUE TITLE
fix:  采集目标弹窗关闭后无法再次打开

### ISSUE THREAD

**Issue by 2020tracey** [TencentBlueKing/bk-audit#261]
系统接入，新建采集时，采集的目标选中一次后就无法再点开重选，这里应该可以重新点开编辑的
<img width="569" alt="image" src="https://github.com/TencentBlueKing/bk-audit/assets/154485076/e52cacfb-e3ea-4e0d-a0b5-1fdf40154f56">

**Comment by OrenZhang** [comment]
同样的问题还出现在版本日志，关闭后也无法二次打开，看下是否组件问题

**Comment by OrenZhang** [comment]
开发分支：dev

**Comment by OrenZhang** [comment]
缺陷重复
